pipeline {
    agent any
    environment {
        PATH = "C:/Users/e039325/Downloads/apache-maven-3.9.8-bin/apache-maven-3.9.8/bin;${env.PATH}"
    }
    stages {
        stage('Clone') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/NandanVasistaBH/microservice101']]
                ])
            }
        }
        stage("Maven") {
            steps {
                bat '''
                cd microservice/eureka
                dir
                mvn install
                cd ../../
                cd microservice/item-service
                dir
                mvn install
                cd ../../
                cd microservice/order-service
                dir
                mvn install
                cd ../../
                cd microservice/dept-service
                dir
                mvn install
                cd ../../
                '''
            }
        }
        stage("Pull an image to check if docker exists"){
            steps{
                bat "docker pull alpine"
            }
        }
        stage("Build Docker image") {
            steps {
                script {
                    try{
                        bat "docker rmi -f billing-system"
                        echo "REMOVED existing docker image and building a new one"
                    }
                    catch(Exception e){
                        echo "Exception occurred "+e.toString()
                    }
                    bat "cd microservice/eureka && docker build -t eureka ."
                    bat "cd microservice/dept-service && docker build -t dept-service ."
                    bat "cd microservice/order-service && docker build -t order-service ."
                    bat "cd microservice/item-service && docker build -t item-service ."
                }
            }
        }
    }
}